[project]
site_name = "FRCDesign.org"
site_description = "A community driven learning course, and resource hub for FRC Design and CAD, using Onshape"
site_author = "FRCDesign Team"
site_url = "https://zensical.frcdesign.org/"
repo_url = "https://github.com/frcdesign/FRCDesign-Zensical"
repo_name = "FRCDesign.org"
extra_css = ["stylesheets/extra.css", "stylesheets/slides.css", "stylesheets/yt-embed.css"]
extra_javascript = ["javascripts/slides.js", "javascripts/yt-embed.js", "javascripts/marked.js", "javascripts/dir_overrides.js"]
docs_dir = "docs"

nav = [
    {"Home" = "index.md"},
    {"Website Feature Guide" = "website-feature-guide/index.md"},
    {"Learning Course" = [
        "learning-course/index.md",
        {"Course Setup" = [
            {"New to CAD" = "learning-course/course-setup/new-to-cad.md"},
            {"New to Onshape" = [
                {"Account Setup" = "learning-course/course-setup/new-to-onshape/account-setup.md"},
                {"Performance Tuning" = "learning-course/course-setup/new-to-onshape/performance-tuning.md"},
                {"Documents Page" = "learning-course/course-setup/new-to-onshape/documents-page.md"}
            ]},
            {"Required Course Tools" = [
                {"Custom Features" = "learning-course/course-setup/required-course-tools/featurescripts.md"},
                {"Part Library" = "learning-course/course-setup/required-course-tools/part-library.md"},

            ]}
        ]},
        {"Stage 3" = "learning-course/stage3/3A/introduction.md"},
        {"Stage 4" = "learning-course/stage4.md"}
    ]},
    {"Other Resources" = [
        "resources/index.md",
        {"Glossary" = "resources/glossary.md"},
        {"CAD Resources" = [
            {"FRCDesignLib" = "resources/frcdesignlib.md"},
            {"KrayonCAD" = "resources/krayonCAD.md"},
            {"Featurescript List" = "resources/featurescripts.md"},
            {"Featurescript Help" = "resources/featurescript-help.md"}
        ]},
        {"Game History" = [
            {"Overview" = "resources/game-history/overview.md"},
            {"Foundational Era (1992-2002)" = [
                {"Maize Craze (1992)" = "resources/game-history/1-foundational-era/1992-maize-craze.md"},
                {"Rug Rage (1993)" = "resources/game-history/1-foundational-era/1993-rug-rage.md"},
                {"Tower Power (1994)" = "resources/game-history/1-foundational-era/1994-tower-power.md"},
                {"Ramp 'n Roll (1995)" = "resources/game-history/1-foundational-era/1995-ramp-n-roll.md"},
                {"Hexagon Havoc (1996)" = "resources/game-history/1-foundational-era/1996-hexagon-havoc.md"},
                {"Toroid Terror (1997)" = "resources/game-history/1-foundational-era/1997-toroid-terror.md"},
                {"Double Trouble (1998)" = "resources/game-history/1-foundational-era/1998-double-trouble.md"},
                {"Ladder Logic (1999)" = "resources/game-history/1-foundational-era/1999-ladder-logic.md"},
                {"Co-Opertition FIRST (2000)" = "resources/game-history/1-foundational-era/2000-coopertition-first.md"},
                {"Diabolical Dynamics (2001)" = "resources/game-history/1-foundational-era/2001-diabolical-dynamics.md"},
                {"Zone Zeal (2002)" = "resources/game-history/1-foundational-era/2002-zone-zeal.md"}
            ]},
            {"Alliance Era (2003-2007)" = [
                {"Stack Attack (2003)" = "resources/game-history/2-alliance-era/2003-stack-attack.md"},
                {"FIRST Frenzy (2004)" = "resources/game-history/2-alliance-era/2004-first-frenzy.md"},
                {"Triple Play (2005)" = "resources/game-history/2-alliance-era/2005-triple-play.md"},
                {"Aim High (2006)" = "resources/game-history/2-alliance-era/2006-aim-high.md"},
                {"Rack 'n Roll (2007)" = "resources/game-history/2-alliance-era/2007-rack-n-roll.md"}
            ]},
            {"Control Era (2008-2015)" = [
                {"FIRST Overdrive (2008)" = "resources/game-history/3-control-era/2008-first-overdrive.md"},
                {"Lunacy (2009)" = "resources/game-history/3-control-era/2009-lunacy.md"},
                {"Breakaway (2010)" = "resources/game-history/3-control-era/2010-breakaway.md"},
                {"Logo Motion (2011)" = "resources/game-history/3-control-era/2011-logo-motion.md"},
                {"Rebound Rumble (2012)" = "resources/game-history/3-control-era/2012-rebound-rumble.md"},
                {"Ultimate Ascent (2013)" = "resources/game-history/3-control-era/2013-ultimate-ascent.md"},
                {"Aerial Assist (2014)" = "resources/game-history/3-control-era/2014-aerial-assist.md"},
                {"Recycle Rush (2015)" = "resources/game-history/3-control-era/2015-recycle-rush.md"}
            ]},
            {"Disney Era (2016-2021)" = [
                {"FIRST Stronghold (2016)" = "resources/game-history/4-disney-era/2016-stronghold.md"},
                {"FIRST Steamworks (2017)" = "resources/game-history/4-disney-era/2017-steamworks.md"},
                {"FIRST Power Up (2018)" = "resources/game-history/4-disney-era/2018-power-up.md"},
                {"Destination: Deep Space (2019)" = "resources/game-history/4-disney-era/2019-deep-space.md"},
                {"Infinite Recharge (2020)" = "resources/game-history/4-disney-era/2020-infinite-recharge.md"}
            ]},
            {"Modern Era (2022-Present)" = [
                {"Rapid React (2022)" = "resources/game-history/5-modern-era/2022-rapid-react.md"},
                {"Charged Up (2023)" = "resources/game-history/5-modern-era/2023-charged-up.md"},
                {"Crescendo (2024)" = "resources/game-history/5-modern-era/2024-crescendo.md"},
                {"Reefscape (2025)" = "resources/game-history/5-modern-era/2025-reefscape.md"}
            ]}
        ]},
        {"Design Challenges" = [
            {"Overview" = "resources/design-challenges/overview.md"},
            {"Week 1" = "resources/design-challenges/week1.md"},
            {"Week 2" = "resources/design-challenges/week2.md"},
            {"Week 3" = "resources/design-challenges/week3.md"},
            {"Week 4" = "resources/design-challenges/week4.md"},
            {"Week 5" = "resources/design-challenges/week5.md"}
        ]}
    ]},
    {"Changelog" = [
        {"Site Updates" = "resources/site-changelog.md"},
        {"Reference Guide" = "resources/changelog.md"}
    ]}


]

[project.theme]
variant = "modern"
favicon = "/assets/images/icon.svg"
language = "en"

features = [
    "content.action.edit",
    "content.code.annotate",
    "header.autohide",
    "navigation.footer",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "navigation.tabs",
    # "navigation.expand",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress"
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "green"
accent = "green"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "green"
accent = "green"

[project.theme.icon]
#logo = "./docs/assets/images/main-logo.svg"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/frcdesign/FRCDesign-Zensical"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/jJePmxcBYm"
name = "Development Discord Server"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.blocks.caption]